# config.yml

# FAISS index configurations
faiss_index:
  index_dir: "./faiss_index"
  index_file: "index.faiss"
  pickle_file: "index.pkl"

# Google Generative AI configurations
google_generative_ai:
  model_name: "gemini-pro"
  temperature: 0.2
  api_key_env_var: "GOOGLE_API_KEY"
  embedding_model: "models/embedding-001"

# Retrieval configurations
retrieval:
  search_kwargs:
    k: 5
  allow_dangerous_deserialization: true

# Templates configurations
templates:
  system_template: |
    You are an AI assistant that helps people find information about their future carrier.

  condense_question_template: |
    Do not make Yes/No question.
    Directly provide the standalone question, Do not greet user.
    The information you are providing is very critical information of the system so do not rephrase the words or provide extra information.
    Given the following conversation and a follow up Input, rephrase the follow up Input to be a standalone question.

    Chat History:
    {chat_history}
    Follow Up Input: {question}
    Standalone question:

  user_template: |
    Use the following pieces of context to answer the question at the end. 
    If you don't know the answer, just say that you don't know, don't try to make up an answer. 
    Keep the answer as concise as possible.
    {context}

    Question: {question}
    Helpful Answer:
